apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-backend
  labels:
    app: golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang
  template: 
    metadata:
      labels:
        app: golang
    spec: 
      containers:
      - name: tutu-project
        image: tutu1008/my-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7004
---
apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  selector:
    app: golang
  ports:
    - protocol: TCP
      port: 7004
      targetPort: 7004
  type: NodePort 


